### ISSUE TITLE
Cool project, but misleading demo

### ISSUE THREAD

**Issue by owen-d** [Shogan/kube-chaos#3]
The demo shows deletion of Loki pods and from experience I know they don't stay alive long enough for this to be possible.

Much <3 from the Loki team 😉

**Comment by Shogan** [comment]
Hi @owen-d 😁 Thanks for dropping by and commenting on the project! Hah, yes the demo was setup with what I had quickly available on my little humble Raspberry Pi k8s cluster. I'm hoping to get some down time in the near future to work more on this project and add a better / more reliable layer between k8s and the game client. Right now everything is slightly delayed because of the System.Process calls all over the place 😅 

I am also hoping to get more time to check Loki out. I've used a lot of Logstash / Elastic in the past and am very curious (and excited) to get started with Grafana Loki.

All the best.
